== Rest Design


=== Context

We need to follow good REST design, so other developers understand what we are building
without too much explanation.

=== Decision

We follow the Zalando guidelines the best we can.

=== Consequences

We have wrongly implemented this in the way we do patch (we put smaller sub models as patch).
Those are now done on root url but should go to a sub-model URL.

We also do put and post with the ID in both the URL and the body.
The guideline tells us it should be URL only.

It's always comply or explain : so always try to follow the rules of Zalando unless you have
good reason not to. That reason should then be documented here.

=== Status
Approved

==== Date
1 jan 2019

= Zalandoo guid follow up

== Context

We need to follow good REST design, so other developers understand what we are building
without too much explanation.

== Decision

We follow the Zalando guidelines the best we can.

== Consequences

We have wrongly implemented this in the way we do patch (we put smaller sub models as patch).
Those are now done on root url but should go to a sub-model URL.

We also do put and post with the ID in both the URL and the body.
The guideline tells us it should be URL only.

It's always comply or explain : so always try to follow the rules of Zalando unless you have
good reason not to. That reason should then be documented here.

== status

Approved

== Date

1 jan 2019



= Zalandoo guid follow up

|===
|  |status | datum

| *Context*

The Zalando guidline prohibits us to use 422 UNPROCESSABLE_ENTITY

*Decision*

We will need to change our UNPROCESSABLE_ENTITY exceptions

*Consequences*

Undecided:

will be on influence on what we will do with: xAuthUserExtractorParseException

| Open issue
| 15 april 2019

|===

= Zalandoo Error handling

|===
|  |status | datum

| *Context*

Api requests can result in errornous behaviour. The requesting client should be aware that the request was not processed correctly. The HTTP spec defines a number of status codes to identify the error. However status codes only can not represent what actually happened and an application can never respond to an error appropriately without that knowledge. To facilitate that gap the Zalando guidelines specifies a usage of the problem+json object. This approach solves an erroneous response and provides more information to the client.

*Decision*

Use Problem JSON defined in RFC-7807 as body with the appropriate http status code and the media type: "application/problem+json".

*Consequences*

api-error-responses.adoc docs are created with an example

| Open issue
| 29 april 2019

|===
